api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "auto-add-2-cart"
type = "function"
uid = "cc555783-5e17-0d60-2c0b-7cc8b6f0eb61c653073d"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
